### ISSUE TITLE
The older version of level doesn't compile on OS X mojave and Arch Linux

### ISSUE THREAD

**Issue by sbmkvp** [substack/peermaps#2]
The installation with npm doesn't work with both MacOS Mojave and Arch Linux. Encountering the following error,

```
make: *** [leveldown.target.mk:119: Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory '/home/xxxxxxx/Temp/peermaps/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.18.16-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/xxxxxxx/Temp/peermaps/node_modules/leveldown
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/xxxxxxx/Temp/peermaps/package.json'
npm WARN peermaps No description
npm WARN peermaps No repository field.
npm WARN peermaps No README data
npm WARN peermaps No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ucfnbso/.npm/_logs/2018-10-25T15_39_02_631Z-debug.log
```

**Comment by sbmkvp** [comment]
**Solution**
Upgrading the version of level dependency to 4.0.0 fixes the issue. Pull request submitted [here ](https://github.com/peermaps/peermaps/pull/3#issue-225821501)
